language: ruby
rvm:
- 2.1
- 2.2
- 2.0
- 1.9
script: "script/cibuild"
before_script: bundle update
cache: bundler
sudo: false

matrix:
  exclude:
    - rvm: 1.9
      env: JEKYLL_VERSION=3.0.0.beta5

env:
  matrix:
    - ""
    - JEKYLL_VERSION=3.0.0.beta5
